#!/usr/bin/env bash
# "shellcheck" pass

set -o errexit
set -o pipefail
set -o nounset

if [[ $# -lt 3 ]]
then
    echo "usage: plotvmafs JSON_FOLDER -o OUTPUT [OPT_PLOTVMAF_ARGS]" 1>&2
    echo 1>&2
    echo "Call plotmaf.R for each input json found in JSON_FOLDER."
    echo "For optional arguments, see plotvmaf.R  --help"
    exit 1
fi

readarray -d '' inputs < <(find "$1" -maxdepth 1 -name "*.json" -printf "-i\0%p\0")
shift
./plotvmaf.R "${inputs[@]}" "$@"
